[package]
name = "karya_json_benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
karya_json = { path = "../karya_json_core" }
serde_json = "1.0"

[dev-dependencies]
criterion = "0.5"
memory-stats = "1.1.0"

[[bench]]
name = "json_benchmarks"
harness = false